<<<<<<< HEAD
name: ebook
description: A Flutter app for ebooks.

version: 1.0.3+4
publish_to: none
=======
name: flutter_ebook_app
description: A Flutter app for Ebooks

version: 1.0.3+4
>>>>>>> fix-style

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.3
  dartz: ^0.10.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons
  flutter_riverpod: ^2.3.6
  flutter_spinkit: ^5.2.0
  freezed_annotation: ^2.2.0
<<<<<<< HEAD
  

  google_fonts: ^4.0.4
  # mno_shared: ^0.1.3
=======
  google_fonts: ^4.0.4
>>>>>>> fix-style
  path: ^1.8.2
  path_provider: ^2.0.3
  permission_handler: ^10.2.0
  sembast: ^3.4.5
  share_plus: ^4.0.4
  shared_preferences: ^2.1.1
<<<<<<< HEAD
  # iridium_reader_widget:
  #   path: ./packages/iridium/reader_widget
  xml2json: ^5.3.1
=======
  xml2json: ^5.3.1
  iridium_reader_widget:
    path: ./packages/iridium/reader_widget
>>>>>>> fix-style

dependency_overrides:
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed: ^2.3.4
  build_runner: ^2.0.3
  dart_code_metrics: ^5.7.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
